In [2]:
import pandas as pd

In [7]:
#df = pd.read_csv('/SGRNJ06/randd/USER/zhouyiqi/work/analysis/20250716-cdr1/test/03.mapping_vdj/test_airr.tsv',sep='\t')
df = pd.read_csv('/SGRNJ06/randd/USER/zhouyiqi/work/analysis/bulk_vdj/run1/P25040701/03.mapping_vdj/P25040701_airr.tsv',sep='\t')

In [15]:
df['productive']

0           F
1           T
2           T
3           F
4           T
         ...
128558      F
128559    NaN
128560      F
128561    NaN
128562    NaN
Name: productive, Length: 128563, dtype: object

In [16]:
dft = df[df['productive']=='T']
dft

,sequence_id,sequence,sequence_aa,locus,stop_codon,vj_in_frame,v_frameshift,productive,rev_comp,complete_vdj,...,fwr3_start,fwr3_end,fwr4_start,fwr4_end,cdr3_start,cdr3_end,np1,np1_length,np2,np2_length
1,AACTCC:GAAGGAAATCGGGGGA:2,GCACACAGCAGGAGGACTCCGCCGTGTATCTCTGTGCCAGCAGCTC...,QEDSAVYLCASSSDYNNEQFFGPGTRLTVLEDLKNVFPPEVAVFEPS,TRB,F,T,F,T,T,F,...,7.0,35.0,69.0,98.0,36.0,68.0,CTACAACAA,9.0,NaN,NaN
2,AACTCC:GCCGTGTATCTCTGTG:3,TATCAACGCAGGAGGACTCCGCCGTGTATCTCTGTGCCAGCAGCTC...,QEDSAVYLCASSSDYNNEQFFGPGTRLTVLEDLKNVFPPEVAVFEPS,TRB,F,T,F,T,T,F,...,8.0,35.0,69.0,98.0,36.0,68.0,CTACAACAA,9.0,NaN,NaN
4,AACTCC:TTCCACCTGACGAAAC:5,TCAGCCCATATGAGCGACGCGGCTGAGTACTTCTGTGCTGTGAGTC...,SDAAEYFCAVSLYPNTGNQFYFGTGTSLTVIPNIQNPDPAVYQLRD,TRA,F,T,F,T,T,F,...,12.0,36.0,76.0,108.0,37.0,75.0,TCTATACCCGAACACCGGTAACCAG,25.0,NaN,NaN
5,AACTGA:AAAACGTGTTCCCACC:6,CCTGATTTCCCACACACATCCCCCCCATCTTCTAACACGTTTTTCA...,GKSVQLGVDLGGRRIIKKGGG,TRA,F,T,F,T,F,F,...,NaN,NaN,NaN,NaN,NaN,NaN,GCTAGGTGTAGAT,13.0,NaN,NaN
6,AACTGA:CGAAACCCTCAGCCCA:7,TCAGCCCATATGAGCGACGCGGCTGAGTACTTCTGTGCTGTGAGTC...,SDAAEYFCAVSLYPNTGNQFYFGTGTSLTVIPNIQNPDPAVYQLRD,TRA,F,T,F,T,T,F,...,12.0,36.0,76.0,108.0,37.0,75.0,TCTATACCCGAACACCGGTAACCAG,25.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128546,TTCTGA:GGTGCAACTACTCATC:188018,GGCTGAATTTAAGAAGAGTGAAACCTCCTTCCACCTGACGAAACCC...,AEFKKSETSFHLTKPSAHMSDAAEYFCAVSLYPNTGNQFYFGTGTS...,TRA,F,T,F,T,T,F,...,1.0,82.0,122.0,151.0,83.0,121.0,TCTATACCCGAACACCGGTAACCAG,25.0,NaN,NaN
128548,TTCTGA:TCTGTGGTATCAACGC:188021,ACACGACGCTCTTCCGATCTGTGGTATCAACGCATCTCTTCCGATC...,STQSLHTGYGLGGSDKAPILA*PCHGHQAPLLG,TRA,F,T,F,T,T,F,...,NaN,NaN,NaN,NaN,NaN,NaN,TACCGGGTATGGTCTAGGGGGATCT,25.0,NaN,NaN
128549,TTCTGA:TGTGTTTTGTCGTGCG:188022,TCAGCACTAAGGAAAAGCCTCCAGCAGCTCCTGCTTTCTGAGGGTA...,SSSCFLRVKDRRCGSA*LTSTLSRPYPGRISRTLTPPHTNQKT,TRA,F,T,F,T,T,F,...,22.0,79.0,NaN,NaN,NaN,NaN,AGGGTAAAGGATAGACG,17.0,NaN,NaN
128551,TTGACT:ACTGGGGGATCTGATA:188024,GCACACAGCAGGAGGACTCCGCCGTGTATCTCTGTGCCAGCAGCTC...,QEDSAVYLCASSSDYNNEQFFGPGTRLTVLEDLKNGCKLGGAGVGTSG,TRB,F,T,F,T,T,F,...,7.0,35.0,69.0,98.0,36.0,68.0,CTACAACAA,9.0,NaN,NaN
128552,TTGACT:AGTGCGGCTGGGTCTC:188025,GCACACAGCAGGAGGACTCCGCCGTGTATCTCTGTGCCAGCAGCTC...,QEDSAVYLCASSSDYNNEQFFGPGTRLTVLEDLKNVFPLEVAVFEPS,TRB,F,T,F,T,T,F,...,7.0,35.0,69.0,98.0,36.0,68.0,CTACAACAA,9.0,NaN,NaN

In [8]:
df = df[df['locus'].notna()]

In [11]:
df

,sequence_id,sequence,sequence_aa,locus,stop_codon,vj_in_frame,v_frameshift,productive,rev_comp,complete_vdj,...,fwr3_start,fwr3_end,fwr4_start,fwr4_end,cdr3_start,cdr3_end,np1,np1_length,np2,np2_length
0,AACTCC:AACCACACGTCCACTA:31,TACTACTGTGCTCTGGGTGATGAAAATGCAGGTGCCAAGCTCACAT...,YYCALGDENAGAKLTFGGGTRLTVRPDIQNPEPAVYQLKDPRSQDS...,TRA,F,T,F,T,T,F,...,1.0,9.0,46.0,78.0,10.0,45.0,TGAA,4.0,NaN,NaN
1,AACTCC:AACCACACGTCTACTA:33,TACTACTGTGCTCTGGGTGATGAAAATGCAGGTGCCAAGCTCACAT...,YYCALGDENAGAKLTFGGGTRLTVRPDIQNPEPAVYQLKDPRSQDS...,TRA,F,T,F,T,T,F,...,1.0,9.0,46.0,78.0,10.0,45.0,TGAA,4.0,NaN,NaN
2,AACTCC:AATTTGTTAGAGAGGG:63,GTGTACTACTGTGCTCTGGGGTACCAGGGAGGCAGAGCTCTGATAT...,VYYCALGYQGGRALIFGTGTTVSVSPNIQNPEPAVXQLKDPRSQDS...,TRA,F,T,F,T,T,F,...,1.0,12.0,46.0,78.0,13.0,45.0,G,1.0,NaN,NaN
3,AACTCC:ACACCTAGGAAAGAGG:68,TCGAATCAAGTCTGTAGAGCCGGAGGACTCTGCTGTGTATCTCTGT...,RIKSVEPEDSAVYLCASS*QGRKLRLHLRLRDQAFGNRGSEKCDST...,TRB,T,F,F,F,T,F,...,1.0,46.0,84.0,113.0,47.0,83.0,NaN,0.0,CCG,3.0
4,AACTCC:ACTCAAGACCAGAGCT:82,CTGTGCTATGAGAGGGACAGTGGAGGCAGCAATTACAAACTGACAT...,HPEPRTCCVPVKRSSVSGQHPLP,TRB,F,F,T,F,T,F,...,85.0,114.0,NaN,NaN,NaN,NaN,CAGTTAAAAGATCCTCGGT,19.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1968108,TTGACT:TTTGTGGTGTGACCGG:3978203,GCTCTCTACCTCTGTGCAGTGGCAAATTCTGGGACTTACCAGAGGT...,ALYLCAVANSGTYQRFGTGTKLQVVPNIQNPEPAVYQLKDPRSQDS...,TRA,F,T,F,T,T,F,...,1.0,15.0,46.0,78.0,16.0,45.0,G,1.0,NaN,NaN
1968109,TTGACT:TTTGTGGTGTGACTGG:3978204,GCTCTCTACCTCTGTGCAGTGGCAAATTCTGGGACTTACCAGAGGT...,ALYLCAVANSGTYQRFGTGTKLQVVPNIQNPEPAVYQLKDPRSQDS...,TRA,F,T,F,T,T,F,...,1.0,15.0,46.0,78.0,16.0,45.0,G,1.0,NaN,NaN
1968110,TTGACT:TTTTCGAGCGGGCTGG:3978206,CATCTATGACAGTTTTAAATGCATATCTTGAAGACAGAGGCTTATA...,SMTVLNAYLEDRGLYLCGASGTNAEQFFGPGTRLTVLEDLRNVTPPKVS,TRB,F,T,F,T,T,F,...,1.0,53.0,84.0,113.0,54.0,83.0,C,1.0,A,1.0
1968111,TTGACT:TTTTGGACTCATCGGG:3978212,TCTACATTGGCTCTGCAGGCCTAGAGTATTCTGCCATGTACCTCTG...,YIGSAGLEYSAMYLCASSRDPPGNTLYFGEGSRLIVVEDLRNVTPPKVS,TRB,F,T,F,T,T,F,...,1.0,47.0,84.0,113.0,48.0,83.0,TCCAC,5.0,NaN,NaN
1968112,TTGACT:TTTTTTTCTCTTAGAG:3978222,CTATGACAGTTTTAAATGCAGATCTTGAAGACAGAGGCTTATATCT...,MTVLNADLEDRGLYLCGALTGGYAEQFFGPGTRLTVLEDLRNVTPPKVS,TRB,F,T,F,T,T,F,...,1.0,50.0,84.0,113.0,51.0,83.0,TT,2.0,A,1.0

In [9]:
grouped = df.groupby(['locus', 'cdr1_aa', 'cdr2_aa'], dropna=False).size().reset_index(name='umis')
grouped['percent'] = grouped['umis'] / grouped['umis'].sum() * 100
grouped = grouped.sort_values(by='umis', ascending=False)
grouped.to_csv('/SGRNJ06/randd/USER/zhouyiqi/work/analysis/20250716-cdr1/cdr1_cdr2_umi_count.csv', index=False)
grouped.head(10)

     locus cdr1_aa cdr2_aa    umis    percent
2013   TRB     NaN     NaN  880162  46.636955
1459   TRA     NaN     NaN  851311  45.108233
1130   TRA     NaN   LVPGP   77007   4.080353
961    TRA     NaN      GT   20985   1.111928
1011   TRA     NaN  IFSPFL   20010   1.060266
2028   TRD     NaN     NaN   15435   0.817851
212    TRA     GTQ     NaN    3491   0.184977
2049   TRG     NaN     NaN    2766   0.146561
876    TRA     NaN      D*    2265   0.120015
1135   TRA     NaN   LVPRP    1960   0.103854

In [10]:
grouped = df.groupby(['locus', 'cdr1_aa', 'cdr2_aa']).size().reset_index(name='umis')
grouped['percent'] = grouped['umis'] / grouped['umis'].sum() * 100
grouped.sort_values(by='umis', ascending=False).head(10)

   locus cdr1_aa  cdr2_aa  umis    percent
37   TRB   SNHLY      FYN   194  45.327103
29   TRB  NSQYPW   LRSPGD   109  25.467290
14   TRA     SEY    GYKDY    35   8.177570
2    TRA  DPNSYY      VFS    13   3.037383
21   TRB  GKSSPN    SITVG    13   3.037383
25   TRB   NGHSY   FQNEDI     6   1.401869
27   TRB   NNHDY   SYVADS     5   1.168224
6    TRA  DSTFNY        I     4   0.934579
12   TRA      PN  VITAGQK     3   0.700935
28   TRB   NSHNY        S     3   0.700935

In [12]:
grouped['umis'].sum()

428

In [14]:
428 / 1887263 * 100

0.022678344247728056